- Tuan Tran
- A20357888
- CS595/CS577 - Spring 2019

## A.

In [38]:
import numpy as np
import math
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.array([-1,1,3])

In [39]:
#Part 1
print("1. 2A-B = {}".format(2*A - B))

#Part 2
print("2. ||A|| = {}".format(np.linalg.norm(A)))

x = np.array([1,0,0])
cos_theta = (np.dot(A,x))/(np.linalg.norm(A)*np.linalg.norm(x))
print("Angle between A and positive x-axis: {} degree".format(math.acos(cos_theta)*(180/math.pi)))

#Part 3
print("3. Unit vector in direction of A: {}".format(A/np.linalg.norm(A)))

#Part 4
print("4. Direction cosines of A are: {}".format(A/np.linalg.norm(A)))

#Part 5 <?> dot or scalar product?
print("5. A . B = {} and B . A = {}".format(np.dot(A,B),np.dot(B,A)))

#part 6
cos_theta = (np.dot(A,B))/(np.linalg.norm(A)*np.linalg.norm(B))
print(math.acos(cos_theta))
print("6. Angle between A and B is {} degree".format(math.acos(cos_theta)*(180/math.pi)))

#Part 7
print("7. A vector (x,y,z) perpendicular to A is any vector satisfying: {}x+{}y+{}z=0".format(A[0],A[1],A[2]))
print("for example: (3,2,-7/3). This vector dot product with A is: {}".format(np.dot([3,2,-7/3],A)))

#Part 8
print("8. A x B = {} and B x A = {}".format(np.cross(A,B),np.cross(B,A)))

#Part 10 <?>

#Part 11
print("11. A tranpose B = {} and A B tranpose = {}".format(np.dot(A.T,B),np.dot(A,B.T)))

1. 2A-B = [-2 -1  0]
2. ||A|| = 3.7416573867739413
Angle between A and positive x-axis: 74.498640433063 degree
3. Unit vector in direction of A: [0.26726124 0.53452248 0.80178373]
4. Direction cosines of A are: [0.26726124 0.53452248 0.80178373]
5. A . B = 32 and B . A = 32
0.2257261285527342
6. Angle between A and B is 12.933154491899135 degree
7. A vector (x,y,z) perpendicular to A is any vector satisfying: 1x+2y+3z=0
for example: (3,2,-7/3). This vector dot product with A is: 0.0
8. A x B = [-3  6 -3] and B x A = [ 3 -6  3]
11. A tranpose B = 32 and A B tranpose = 32


## B.

In [40]:
A = np.matrix([[1,2,3],[4,-2,3],[0,5,-1]])
B = np.matrix([[1,2,1],[2,1,-4],[3,-2,1]])
C = np.matrix([[1,2,3],[4,5,6],[-1,1,3]])
#part 1
print("1. 2A-B = \n{}".format(2*A - B))

#Part 2
print("2. AB = \n{} \nand BA = \n{}".format(A*B,B*A))

#Part 3
print("3. (AB).T = \n{} \nand B.T A.T = \n{}".format((A*B).T,B.T*A.T))

#Part 4
print("4. |A| = {} and |C| = {}".format(np.linalg.det(A),np.linalg.det(C)))

#Part 6
print("6. A^-1 = \n{} \nand B^-1 = \n{}".format(np.linalg.inv(A),np.linalg.inv(B)))

1. 2A-B = 
[[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]
2. AB = 
[[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]] 
and BA = 
[[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]
3. (AB).T = 
[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]] 
and B.T A.T = 
[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]
4. |A| = 54.999999999999964 and |C| = 0.0
6. A^-1 = 
[[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]] 
and B^-1 = 
[[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


## C.

In [41]:
A = np.array([[1,2],[3,2]])
B = np.array([[2,-2],[-2,5]])

#part 1
w,v = np.linalg.eig(A)
print("1. eigenvalues = {} and (normalized) eigenvectors = \n{}".format(w,v))

#part 3
wA, vA = np.linalg.eig(A)
print("3. Dot product between eigenvectors of A = {}".format(np.dot(vA[:,0],vA[:,1])))

#Part 4
wB, vB = np.linalg.eig(B)
print("4. Dot product between eigenvectors of B = {}".format(np.dot(vB[:,0],vB[:,1])))

#Part 5


1. eigenvalues = [-1.  4.] and (normalized) eigenvectors = 
[[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]
3. Dot product between eigenvectors of A = -0.19611613513818388
4. Dot product between eigenvectors of B = 0.0
